config/routes.rb
Rails.application.routes.draw do

  get '/', to: 'welcome#index'

  resources :tasks
  # get '/tasks', to: 'tasks#index'
  # get '/tasks/new', to: 'tasks#new'
  # post '/tasks', to: 'tasks#create'
  # get '/tasks/:id', to: 'tasks#show'
  # get '/tasks/:id/edit', to: 'tasks#edit'
  # patch '/tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

    def index
        @tasks = Task.all
    end

    def show
        @task = Task.find(params[:id])
    end

    def new
    end

    def create
        task = Task.new(task_params)
        task.save
        redirect_to tasks_path
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        task = Task.find(params[:id])
        task.update(task_params)
        task.save
        redirect_to task_path(task)
    end

    def destroy
        Task.destroy(params[:id])
        redirect_to tasks_path
    end

    private

    def task_params
        params.permit(:title, :description)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_tag(task_path(@task), method: :patch) do %>
    <h2>Edit Task</h2>
    
    <%= label_tag :title %>
    <%= text_field_tag :title, "#{@task.title}" %></br>
    
    <%= label_tag :description %>
    <%= text_area_tag :description, "#{@task.description}" %></br>

    <%= submit_tag "submit" %>
<% end %>

app/views/tasks/index.html.erb
<h1>All Tasks</h1>

<%= button_to "home", '/', method: :get %>

<% @tasks.each do |task| %>
    <section id = "task-<%= task.id %>">
    <h3><%= link_to "#{task.title}", task_path(task) %></h3>
    <p><%= task.description %></p>
    </section>
    
    <% end %>

app/views/tasks/new.html.erb
<%= form_tag(tasks_path, method: :post) do %>
    <h2>Enter A New Task</h2>
    
    <%= label_tag :title %>
    <%= text_field_tag :title %></br>
    
    <%= label_tag :description %>
    <%= text_area_tag :description %></br>

    <%= submit_tag "submit" %>
<% end %>

app/views/tasks/show.html.erb
<%= button_to "Task Index", "/tasks" %>

<h1><%= @task.title %></h1>
<p><%= @task.description %></p>
<%= button_to "Edit", "/tasks/#{@task.id}/edit", method: :get %>
<%= button_to "Delete", "/tasks/#{@task.id}", method: :delete %>

app/views/welcome/index.html.erb
<h1>Welcome to the Task Manager</h1>

<ul>
    <li><%= link_to 'Task Index', tasks_path %></li>
    <li><%= link_to 'New Task', new_task_path %></li>
</ul>